
-- Tables dropping

DROP TABLE BUDGET;
DROP TABLE ESPECE;
DROP TABLE ECHANTILLON;
DROP TABLE PARTICIPER_CAMPAGNE;
DROP TABLE POSSEDER_HABILITATION;
DROP TABLE INCULRE_EQUIPEMENT;
DROP TABLE NECESSITER_HABILITATION;
DROP TABLE HABILITATION;
DROP TABLE EQUIPEMENT;
DROP TABLE MAINTENANCE;
DROP TABLE PERSONNEL;
DROP TABLE CAMPAGNE;
DROP TABLE PLATEFORME;
