-- Functions and Triggers dropping

DROP TRIGGER checkCampagneValidity;
DROP TRIGGER checkBudget;
DROP TRIGGER checkBudgetUpdate;

DROP FUNCTION plateformeAvailable;
DROP FUNCTION remainingBudget;

-- Tables dropping

DROP TABLE BUDGET;
DROP TABLE ECHANTILLON;
DROP TABLE ESPECE;
DROP TABLE PARTICIPER_CAMPAGNE;
DROP TABLE POSSEDER_HABILITATION;
DROP TABLE INCLURE_EQUIPEMENT;
DROP TABLE NECESSITER_HABILITATION;
DROP TABLE HABILITATION;
DROP TABLE EQUIPEMENT;
DROP TABLE MAINTENANCE;
DROP TABLE PERSONNEL;
DROP TABLE CAMPAGNE;
DROP TABLE PLATEFORME;
